version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  server:
    build:
      context: ./server
      args:
        UID: ${UID}
        GID: ${GID}
    restart: always
    ports:
      - "8080:8080"
    environment:
      TZ: ${TZ}
    env_file:
      - .env
    depends_on:
      - db
